In [1]:
#Code for kohonen neural network
import numpy as np
import matplotlib.pyplot as plt
from numpy import binary_repr
import random
np.random.seed(100)

In [2]:
def genData(input_line):
    print('Input Lines: ' + str(input_line)) # no of bits in the input, 101 has 3 bits so 3 input line in perceptron\n",
    number_of_elements = pow(2,input_line) #total combination\n",


    # Making inputs\n",
    inputs = []

    i = 0
    for i in range(0,number_of_elements, 1):
        tmp = list(binary_repr(i,input_line)) #params=value, length, this returns binary patterns for value of length\n",
        inputs.append(tmp)
        i = i+1
    inputs = np.array(inputs)
    return (inputs.astype(np.float)) #convert string into float and int"

In [10]:
def split_dataset(inputs, ratio): #split data with train data ratio=ratio\n",
    no = round((len(inputs) * ratio)/2)
    no_test = round(len(inputs)/2) - no
    train_x= []
    test_x= []
    for i in range(0, no):
        train_x.append(inputs[i])
    for i in range(no, no+no_test):
        test_x.append(inputs[i])
    for i in range(round(len(inputs)/2), no+round(len(inputs)/2)):
        train_x.append(inputs[i])
    for i in range(no+round(len(inputs)/2), len(inputs)):
        test_x.append(inputs[i])

    return (np.array(train_x), np.array(test_x))

In [4]:
def calculate_distance(x, w):
    return sum((x-w)**2)

In [5]:
def train_kohonen(x, output_class):
    nb_input = len(x) #total input
    nb_input_layer_node = len(x[0]) #number of input layer node
    W = np.random.random((output_class, nb_input_layer_node)) #weights
    final_W = []
    distance = [[0, 0] for i in range(output_class)]
    print('weight',W)
    N = 3 #initial radius
    ita = np.random.random() #gain term
    #ita = 0.8
    print('Ita',ita)
    i = 0
    #print('HIIHIHH',distance)
    flag = False
    k = 0
    while True:
        if i == nb_input:
            break
        for j in range(output_class):
            distance[j][0] = calculate_distance(x[i], W[j])
            distance[j][1] = j
        #print('distance',distance)
        dist = sorted(distance,key=lambda l:l[0])
        print('sorted distance',dist)
        
        #update weights
        for j in range(N):
            W[dist[j][1]] = W[dist[j][1]] + ita*(x[i]-W[dist[j][1]])#dist[j][1] will give index with lowest distance
        if flag == True:
            i = i + 1 #next sample
            flag = False #resetting flag
            N = 3 #reset neighbor
            print('Weight', W)
            print('Index of output node', dist[0][1])
            final_W.append([W[dist[0][1]], dist[0][1]])
            continue
            
        N = round(N - ita * N)
        if N == 1:
            flag = True
    print('\n\n')
    for i, j in final_W:
        print(i, j)
    return (final_W, output_class, ita)

In [6]:
def test_kohonen(x, W, output_class, ita):
    nb_input = len(x)
    distance = [[0, 0] for i in range(output_class)]
    
    for i in range(nb_input):
        for j in range(output_class):
                distance[j][0] = calculate_distance(x[i], W[j][0])
                distance[j][1] = j
        dist = sorted(distance,key=lambda l:l[0])
        print('Pattern:', x[i], 'Predicted:', dist[0][1])

In [14]:
if __name__=="__main__":
    nb_of_line = 5
    nb_hidden = 5
    inputs = genData(nb_of_line) #log2(nb_class) must be binary
    #print(inputs)
    #print(classes)
    
    train_ratio = 0.8
    (train_x, test_x) = split_dataset(inputs,train_ratio)
    #print(ita, threshold)
    #step 2
    #train_perceptron(train_x, train_y)
    #print(train_x)
    
    (final_W, output_class, ita) = train_kohonen(train_x, nb_hidden)
    k = 0
    for i, j in final_W:
        print('Pattern:',train_x[k], 'Predicted:', j)
        k = k + 1
    print('\nTesting\n')
    test_kohonen(test_x, final_W, output_class, ita)

Input Lines: 5
weight [[ 0.35950784  0.59885895  0.35479561  0.34019022  0.17808099]
 [ 0.23769421  0.04486228  0.50543143  0.37625245  0.5928054 ]
 [ 0.62994188  0.14260031  0.9338413   0.94637988  0.60229666]
 [ 0.38776628  0.363188    0.20434528  0.27676506  0.24653588]
 [ 0.173608    0.96660969  0.9570126   0.59797368  0.73130075]]
Ita 0.3403852228374361
sorted distance [[0.46140404659633505, 3], [0.76120007441614168, 0], [0.8069562440556528, 1], [2.5476173316020234, 2], [2.7727204755550421, 4]]
sorted distance [[0.20075304991180587, 3], [0.33119179959386991, 0], [0.3510999271345242, 1], [2.5476173316020234, 2], [2.7727204755550421, 4]]
sorted distance [[0.08734597658210512, 3], [0.14409878795973499, 0], [0.3510999271345242, 1], [2.5476173316020234, 2], [2.7727204755550421, 4]]
Weight [[ 0.15641886  0.26055853  0.15436861  0.14801392  0.07748155]
 [ 0.15678661  0.02959182  0.33339004  0.24818168  0.3910232 ]
 [ 0.62994188  0.14260031  0.9338413   0.94637988  0.60229666]
 [ 0.111286